// AUTOGENERATED from engine/battle.ts. Edit the source, not this file.
// engine/battle.ts — deterministic 1v1 battle simulator (Wildex v0.2).
//
// Pure TypeScript. Zero runtime dependencies. No React, no Node built-ins, no I/O.
// Runs byte-for-byte identically on Metro (Hermes), Node (Jest), and Deno (Edge Functions).
//
// Spec refs:
//   spec/architecture.md §2  (engine/ module boundary — no external imports)
//   spec/architecture.md §3  (engine sharing strategy — must be deterministic)
//   DESIGN.md §Battle System (type chart, alternating-attacker pattern)
//   spec/test-plan.md §2.1   (D1-D5 determinism cases)

import { rng } from './rng';
import type { BattleStats, Element, Turn } from './types';

/**
 * Alias for BattleStats. Exported so callers and tests can import a
 * semantically clear name for the simulateBattle argument type.
 */
export type BattleInput = BattleStats;

/** Outcome returned by simulateBattle. */
export type BattleOutcome = {
  /** The `id` of the winning capture, or 'draw' on a seeded-PRNG tie. */
  winnerId: string;
  /** Turn-by-turn log. Shape is stable across all v0.2 callers. */
  log: Turn[];
  /** Total number of turns taken (always <= MAX_TURNS). */
  totalTurns: number;
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Hard cap on turns to guarantee termination for any stat combination. */
export const MAX_TURNS = 200;

/**
 * Type effectiveness chart.
 *
 * `TYPE_CHART[attacker][defender]` is the damage multiplier.
 * Missing entries (or `unknown`) resolve to 1.0 (neutral).
 *
 * Design constraint (DESIGN.md): "Loose chart on purpose — players should be
 * able to win with most matchups."  Values stay in [0.7, 1.4]; no hard 2× counters.
 *
 * Exported so tests can verify every cell exhaustively.
 */
export const TYPE_CHART: Record<Element, Partial<Record<Element, number>>> = {
  beast:   { insect: 1.3, avian: 1.2, reptile: 0.8 },
  avian:   { insect: 1.4, reptile: 1.1, aquatic: 0.8 },
  aquatic: { beast: 1.1, fungal: 1.2, flora: 0.7 },
  reptile: { aquatic: 1.2, insect: 1.1, avian: 0.8 },
  insect:  { flora: 1.4, fungal: 1.2, avian: 0.7 },
  flora:   { aquatic: 1.3, beast: 0.8, fungal: 0.7 },
  fungal:  { flora: 1.3, insect: 0.8, beast: 1.1 },
  unknown: {},
};

// All valid element keys — used for exhaustiveness checks in tests.
export const ELEMENTS: readonly Element[] = [
  'beast', 'avian', 'aquatic', 'reptile', 'insect', 'flora', 'fungal', 'unknown',
] as const;

// ---------------------------------------------------------------------------
// Internal helpers (not exported — covered 100% via simulateBattle)
// ---------------------------------------------------------------------------

/** Build the deterministic seed string from the two capture IDs and a timestamp. */
function buildSeed(idA: string, idB: string, timestamp: number): string {
  return `${idA}:${idB}:${timestamp}`;
}

/**
 * Compute raw damage for one attack.
 *
 * Formula (ported from lib/battle.ts v0.1):
 *   base = (attacker.attack * 2) / max(1, defender.defense)
 *   mult = typeMultiplier * (crit ? 1.6 : 1)
 *   dmg  = max(1, round(base * mult * (0.9 + r * 0.2)))
 *
 * The random variance window [0.9, 1.1] keeps damage interesting without
 * swinging more than ±10% from the deterministic baseline.
 * A crit (r < 0.08 → ~8% chance) deals a flat 1.6× instead.
 */
function calcDamage(
  att: BattleStats,
  def: BattleStats,
  r: number,
): { dmg: number; crit: boolean } {
  const crit = r < 0.08;
  const base = (att.attack * 2) / Math.max(1, def.defense);
  const typeMult = TYPE_CHART[att.element]?.[def.element] ?? 1;
  const mult = typeMult * (crit ? 1.6 : 1);
  const dmg = Math.max(1, Math.round(base * mult * (0.9 + r * 0.2)));
  return { dmg, crit };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Simulate a deterministic 1v1 battle between two captures.
 *
 * Determinism guarantee: identical `(captureA.id, captureB.id, timestamp)`
 * always produces identical `{ winnerId, log, totalTurns }` on any runtime.
 *
 * @param captureA  - Stat block + id for the first capture (challenger).
 * @param captureB  - Stat block + id for the second capture (opponent).
 * @param timestamp - Unix epoch ms. Used as the third seed component so
 *                    replaying with the same timestamp reproduces the battle.
 * @returns BattleOutcome with a stable `log` shape.
 */
export function simulateBattle(
  captureA: BattleStats,
  captureB: BattleStats,
  timestamp: number,
): BattleOutcome {
  const seed = buildSeed(captureA.id, captureB.id, timestamp);
  const roll = rng(seed);

  let hpA = captureA.hp;
  let hpB = captureB.hp;
  const log: Turn[] = [];

  // Higher speed goes first; ties go to captureA (explicit, not implicit).
  const aFirst = captureA.speed >= captureB.speed;

  let turn = 0;

  while (hpA > 0 && hpB > 0 && turn < MAX_TURNS) {
    turn++;
    const aTurn = aFirst ? turn % 2 === 1 : turn % 2 === 0;

    if (aTurn) {
      const { dmg, crit } = calcDamage(captureA, captureB, roll());
      hpB -= dmg;
      log.push({ turn, attacker: 'a', damage: dmg, crit });
    } else {
      const { dmg, crit } = calcDamage(captureB, captureA, roll());
      hpA -= dmg;
      log.push({ turn, attacker: 'b', damage: dmg, crit });
    }
  }

  // Tie-break ladder (ported from lib/battle.ts — audit Code-5 fix).
  // Falls through stat comparisons; final fallback is a seeded PRNG draw.
  let winnerId: string;
  if (hpA !== hpB) {
    winnerId = hpA > hpB ? captureA.id : captureB.id;
  } else if (captureA.attack !== captureB.attack) {
    winnerId = captureA.attack > captureB.attack ? captureA.id : captureB.id;
  } else if (captureA.speed !== captureB.speed) {
    winnerId = captureA.speed > captureB.speed ? captureA.id : captureB.id;
  } else if (captureA.defense !== captureB.defense) {
    winnerId = captureA.defense > captureB.defense ? captureA.id : captureB.id;
  } else {
    winnerId = roll() < 0.5 ? captureA.id : captureB.id;
  }

  return { winnerId, log, totalTurns: turn };
}
