// AUTOGENERATED from engine/rng.ts. Edit the source, not this file.
// Single source of truth for the deterministic FNV-style PRNG used by stat
// generation (lib/stats.ts) and battle simulation (lib/battle.ts). The Edge
// Function (`supabase/functions/_shared/battle.ts`) inlines the same logic so
// it stays Deno-self-contained — if you edit one, edit the other.
//
// `Math.imul` keeps the FNV step a true 32-bit integer hash. JS multiplication
// of `(h ^ c) * 16777619` overflows to a float after ~2 characters and the
// mixing is effectively lossy — `Math.imul` is the documented fix (audit Code-6).

export function rng(seed: string) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < seed.length; i++) h = Math.imul(h ^ seed.charCodeAt(i), 16777619);
  return () => {
    h = (Math.imul(h, 1664525) + 1013904223) >>> 0;
    return h / 0xffffffff;
  };
}
