// AUTOGENERATED from engine/stats.ts. Edit the source, not this file.
// Deterministic stat generation for a captured animal.
// Pure TypeScript — no I/O, no React, no Supabase. Runs on Metro and Deno unchanged.
//
// Signature change from v0.1: arguments are flat (captureId, taxonId, iconicTaxon, score)
// instead of (captureId, IdSuggestion).

import { rng } from './rng';
import type { BattleStats, Element, Rarity } from './types';

// Re-export for callers that import types from this module.
export type { BattleStats, Element, Rarity } from './types';

// ---------------------------------------------------------------------------
// Exported lookup tables — tests iterate over these directly (S1, S2)
// ---------------------------------------------------------------------------

/** Maps iNaturalist iconic taxon class name → game element. */
export const ELEMENT_MAP: Readonly<Record<string, Element>> = {
  Mammalia: 'beast',
  Aves: 'avian',
  Actinopterygii: 'aquatic',
  Amphibia: 'aquatic',
  Reptilia: 'reptile',
  Insecta: 'insect',
  Arachnida: 'insect',
  Mollusca: 'aquatic',
  Plantae: 'flora',
  Fungi: 'fungal',
};

/**
 * Ordered rarity thresholds. Each entry: [minExclusiveScore, rarity].
 * Evaluated top-to-bottom; the first entry whose threshold is exceeded wins.
 * Exported so tests can iterate and assert monotonicity without hardcoding magic numbers.
 */
export const RARITY_THRESHOLDS: ReadonlyArray<readonly [number, Rarity]> = [
  [0.97, 'legendary'],
  [0.9, 'epic'],
  [0.75, 'rare'],
  [0.5, 'uncommon'],
] as const;

// ---------------------------------------------------------------------------
// Internal tables
// ---------------------------------------------------------------------------

const RARITY_BUDGET: Readonly<Record<Rarity, number>> = {
  common: 250,
  uncommon: 300,
  rare: 360,
  epic: 420,
  legendary: 500,
};

/** Per-element stat bias weights: [HP, ATK, DEF, SPD, SPC]. */
const ELEMENT_BIAS: Readonly<Record<Element, readonly [number, number, number, number, number]>> = {
  beast:   [1.1, 1.2, 1.0, 0.9, 0.8],
  avian:   [0.9, 1.0, 0.8, 1.4, 0.9],
  aquatic: [1.0, 0.9, 1.0, 1.0, 1.1],
  reptile: [1.0, 1.1, 1.2, 0.8, 0.9],
  insect:  [0.8, 1.0, 0.8, 1.3, 1.1],
  flora:   [1.3, 0.7, 1.3, 0.6, 1.1],
  fungal:  [1.0, 0.8, 1.0, 0.8, 1.4],
  unknown: [1.0, 1.0, 1.0, 1.0, 1.0],
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function rarityFromScore(score: number): Rarity {
  for (const [threshold, rarity] of RARITY_THRESHOLDS) {
    if (score > threshold) return rarity;
  }
  return 'common';
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Deterministically roll battle stats for a capture.
 *
 * @param captureId   - Stable capture UUID; seeds the PRNG.
 * @param taxonId     - iNaturalist taxon ID (not used in the stat formula; reserved for
 *                      future element overrides and passed through for caller convenience).
 * @param iconicTaxon - iNaturalist iconic taxon class name (e.g. "Aves", "Mammalia").
 * @param score       - iNaturalist identification confidence in [0, 1]. Values outside
 *                      this range are clamped; NaN/missing is treated as 0.
 * @returns Fully typed BattleStats object. Same inputs always produce the same output.
 */
export function rollStats(
  captureId: string,
  taxonId: number,
  iconicTaxon: string,
  score: number,
): BattleStats {
  // taxonId is part of the public contract and reserved for future use.
  void taxonId;

  const element: Element = ELEMENT_MAP[iconicTaxon] ?? 'unknown';

  // Clamp score to [0, 1]; guard against NaN / negative / out-of-range iNat values.
  const clampedScore = Math.max(0, Math.min(1, Number(score) || 0));
  const rarity = rarityFromScore(clampedScore);
  const budget = RARITY_BUDGET[rarity];

  const r = rng(captureId);
  const bias = ELEMENT_BIAS[element];

  // Draw 5 random base weights in [0.6, 1.4], then apply element bias.
  const weights: [number, number, number, number, number] = [
    (0.6 + r() * 0.8) * bias[0],
    (0.6 + r() * 0.8) * bias[1],
    (0.6 + r() * 0.8) * bias[2],
    (0.6 + r() * 0.8) * bias[3],
    (0.6 + r() * 0.8) * bias[4],
  ];

  const sum = weights[0] + weights[1] + weights[2] + weights[3] + weights[4];
  const alloc = weights.map((w) => Math.round((w / sum) * budget));

  return {
    id:      captureId,
    hp:      20 + alloc[0],
    attack:   5 + alloc[1],
    defense:  5 + alloc[2],
    speed:    5 + alloc[3],
    special:  5 + alloc[4],
    element,
    rarity,
  };
}
