#!/usr/bin/env ts-node
/**
 * scripts/check-engine-drift.ts
 *
 * CI gate: diffs engine/ against supabase/functions/_shared/engine/ and
 * exits non-zero if any file has drifted. Ignores the one-line autogenerated
 * header that sync-engine.ts prepends to each destination file.
 *
 * Exit codes:
 *   0  — trees are in sync
 *   1  — drift detected or usage error
 *
 * Run:
 *   npx ts-node scripts/check-engine-drift.ts
 *   node --loader ts-node/esm scripts/check-engine-drift.ts
 *
 * Spec: spec/architecture.md §3 (check:engine CI step).
 *
 * Uses Node built-ins only (fs, path, crypto). No new npm dependencies.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const REPO_ROOT = path.resolve(__dirname, '..');
const SRC_DIR   = path.join(REPO_ROOT, 'engine');
const DEST_DIR  = path.join(REPO_ROOT, 'supabase', 'functions', '_shared', 'engine');

const SKIP_DIRS = new Set(['__tests__']);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function collectTsFiles(dir: string): string[] {
  const results: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    throw new Error(
      `check-engine-drift: cannot read directory "${dir}"\n` +
      `  -> ${(err as NodeJS.ErrnoException).message}`
    );
  }
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      results.push(...collectTsFiles(path.join(dir, entry.name)));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

/** SHA-256 hex digest of a string. */
function sha256(content: string): string {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

/**
 * Strips the first line of `content` if it begins with the autogenerated
 * header prefix that sync-engine.ts writes. Returns the rest unchanged.
 *
 * The header format is:
 *   // AUTOGENERATED from engine/<file>. Edit the source, not this file.\n
 */
function stripHeader(content: string): string {
  const PREFIX = '// AUTOGENERATED from engine/';
  if (content.startsWith(PREFIX)) {
    const newlineIdx = content.indexOf('\n');
    if (newlineIdx !== -1) return content.slice(newlineIdx + 1);
  }
  return content;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  // Verify source directory exists.
  if (!fs.existsSync(SRC_DIR)) {
    console.error(
      `check-engine-drift: source directory "${SRC_DIR}" does not exist.\n` +
      `  Is this being run from the repo root?`
    );
    process.exit(1);
  }

  // Verify dest directory exists (sync has not been run yet).
  if (!fs.existsSync(DEST_DIR)) {
    console.error(
      `check-engine-drift: generated directory "${DEST_DIR}" does not exist.\n` +
      `  Run "npm run sync-engine" first, then commit the generated files.`
    );
    process.exit(1);
  }

  const srcFiles = collectTsFiles(SRC_DIR);

  if (srcFiles.length === 0) {
    console.error(
      `check-engine-drift: no *.ts files found in "${SRC_DIR}".\n` +
      `  Nothing to check. Is the engine/ directory populated?`
    );
    process.exit(1);
  }

  const drifted: string[] = [];
  const missingInDest: string[] = [];

  for (const srcPath of srcFiles) {
    const relPath = path.relative(SRC_DIR, srcPath).replace(/\\/g, '/');
    const destPath = path.join(DEST_DIR, relPath);

    // Read source.
    let srcContent: string;
    try {
      srcContent = fs.readFileSync(srcPath, 'utf8');
    } catch (err) {
      throw new Error(
        `check-engine-drift: cannot read source file "${srcPath}"\n` +
        `  -> ${(err as NodeJS.ErrnoException).message}`
      );
    }

    // Check dest exists.
    if (!fs.existsSync(destPath)) {
      missingInDest.push(relPath);
      continue;
    }

    // Read dest and strip the autogenerated header before comparing.
    let destContent: string;
    try {
      destContent = fs.readFileSync(destPath, 'utf8');
    } catch (err) {
      throw new Error(
        `check-engine-drift: cannot read destination file "${destPath}"\n` +
        `  -> ${(err as NodeJS.ErrnoException).message}`
      );
    }

    const destStripped = stripHeader(destContent);

    if (sha256(srcContent) !== sha256(destStripped)) {
      drifted.push(relPath);
    }
  }

  // Also check for files in dest that have no corresponding source.
  const destFiles = collectTsFiles(DEST_DIR);
  const srcRelPaths = new Set(
    srcFiles.map((f) => path.relative(SRC_DIR, f).replace(/\\/g, '/'))
  );
  const orphans: string[] = [];
  for (const destPath of destFiles) {
    const relPath = path.relative(DEST_DIR, destPath).replace(/\\/g, '/');
    if (!srcRelPaths.has(relPath)) {
      orphans.push(relPath);
    }
  }

  // Report and exit.
  const hasDrift = drifted.length > 0 || missingInDest.length > 0 || orphans.length > 0;

  if (!hasDrift) {
    const total = srcFiles.length;
    console.log(`check-engine-drift: OK — ${total} file(s) in sync.`);
    process.exit(0);
  }

  console.error('check-engine-drift: DRIFT DETECTED — engine/ and _shared/engine/ are out of sync.');
  console.error('  Fix: run "npm run sync-engine" and commit the result.\n');

  if (drifted.length > 0) {
    console.error('  Content differs:');
    for (const f of drifted) {
      console.error(`    engine/${f}  vs  supabase/functions/_shared/engine/${f}`);
    }
  }

  if (missingInDest.length > 0) {
    console.error('  Missing from _shared/engine/ (not yet synced):');
    for (const f of missingInDest) {
      console.error(`    ${f}`);
    }
  }

  if (orphans.length > 0) {
    console.error('  Orphaned in _shared/engine/ (no matching source in engine/):');
    for (const f of orphans) {
      console.error(`    ${f}`);
    }
    console.error('  These files should be deleted from _shared/engine/ or added to engine/.');
  }

  process.exit(1);
}

main();
