#!/usr/bin/env ts-node
/**
 * scripts/sync-engine.ts
 *
 * Copies all *.ts files from engine/ into supabase/functions/_shared/engine/,
 * preserving subdirectory structure. Skips __tests__/ subtrees.
 * Prepends a generated-file header to each destination file.
 * Idempotent: re-running overwrites with the same content.
 *
 * Run:
 *   npx ts-node scripts/sync-engine.ts
 *   node --loader ts-node/esm scripts/sync-engine.ts
 *
 * Spec: spec/architecture.md §3 (Engine sharing strategy, option c).
 *
 * Uses Node built-ins only (fs, path). No new npm dependencies.
 */

import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const REPO_ROOT = path.resolve(__dirname, '..');
const SRC_DIR   = path.join(REPO_ROOT, 'engine');
const DEST_DIR  = path.join(REPO_ROOT, 'supabase', 'functions', '_shared', 'engine');

const SKIP_DIRS = new Set(['__tests__']);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Returns all *.ts file paths under `dir`, recursively, skipping any
 * directory whose basename is in SKIP_DIRS.
 */
function collectTsFiles(dir: string): string[] {
  const results: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    throw new Error(
      `sync-engine: cannot read source directory "${dir}"\n` +
      `  -> ${(err as NodeJS.ErrnoException).message}\n` +
      `  Make sure you are running this script from the repo root.`
    );
  }

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      const sub = collectTsFiles(path.join(dir, entry.name));
      results.push(...sub);
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

/**
 * Builds the one-line header comment stamped at the top of every dest file.
 * The check-engine-drift script strips this line before comparing.
 */
function buildHeader(relPath: string): string {
  return `// AUTOGENERATED from engine/${relPath}. Edit the source, not this file.\n`;
}

/**
 * Ensures all intermediate directories for `filePath` exist.
 * Reports which directory it is creating so the user can clean up on failure.
 */
function ensureDir(filePath: string): void {
  const dir = path.dirname(filePath);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch (err) {
    throw new Error(
      `sync-engine: failed to create directory "${dir}"\n` +
      `  -> ${(err as NodeJS.ErrnoException).message}\n` +
      `  If a previous sync failed midway, remove "${DEST_DIR}" and retry.`
    );
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const srcFiles = collectTsFiles(SRC_DIR);

  if (srcFiles.length === 0) {
    console.error(
      `sync-engine: no *.ts files found in "${SRC_DIR}"\n` +
      `  Nothing to sync. Is the engine/ directory populated?`
    );
    process.exit(1);
  }

  let synced = 0;
  let skipped = 0;

  for (const srcPath of srcFiles) {
    const relPath = path.relative(SRC_DIR, srcPath).replace(/\\/g, '/');
    const destPath = path.join(DEST_DIR, relPath);

    const srcContent = (() => {
      try {
        return fs.readFileSync(srcPath, 'utf8');
      } catch (err) {
        throw new Error(
          `sync-engine: cannot read source file "${srcPath}"\n` +
          `  -> ${(err as NodeJS.ErrnoException).message}`
        );
      }
    })();

    const header = buildHeader(relPath);
    const destContent = header + srcContent;

    // Check if dest already has identical content (idempotency fast-path).
    let existingContent: string | null = null;
    try {
      existingContent = fs.readFileSync(destPath, 'utf8');
    } catch {
      // File does not exist yet — that is fine.
    }

    if (existingContent === destContent) {
      skipped++;
      continue;
    }

    ensureDir(destPath);

    try {
      fs.writeFileSync(destPath, destContent, 'utf8');
    } catch (err) {
      throw new Error(
        `sync-engine: failed to write destination file "${destPath}"\n` +
        `  -> ${(err as NodeJS.ErrnoException).message}\n` +
        `  Partial sync may have occurred. Files written so far are valid;\n` +
        `  fix the error and re-run — the script is idempotent.`
      );
    }

    console.log(`  synced: engine/${relPath} -> ${path.relative(REPO_ROOT, destPath)}`);
    synced++;
  }

  const total = srcFiles.length;
  console.log(
    `sync-engine: done. ${synced} file(s) written, ${skipped} file(s) already up-to-date (${total} total).`
  );
}

main();
