-- =============================================================================
-- 0001_profiles.sql — Wildex v0.2 — profiles table + friend-code generator
-- =============================================================================
-- Spec: spec/data-model.md §2.1 (profiles) + §6 Phase A (migration plan).
-- Adds the 1:1 profiles table for auth.users, an 8-char friend_code generator,
-- a handle_new_user() trigger that runs on auth.users insert, and the RLS
-- policies that constrain client access (read own + update own; column-level
-- revokes lock friend_code/is_pro/pro_until to the server side).
--
-- Replayability: every object uses `if not exists` / `create or replace` /
-- `do $$ ... exception when duplicate_object then null; end $$;` guards so
-- re-running this file is a no-op. Naming conventions follow supabase/schema.sql
-- (snake_case object names, lowercase keywords, "policy-name in quotes").
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. profiles table (data-model.md §2.1)
-- -----------------------------------------------------------------------------
-- Mirrors auth.users 1:1. user_id is both PK and FK; on auth.users delete the
-- profile cascades away.  friend_code is the 8-char public handle used by the
-- add-friend Edge Function to resolve a code → uuid under service role
-- (clients cannot enumerate; see RLS section below).
create table if not exists profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  friend_code  text not null unique,
  display_name text,
  is_pro       boolean not null default false,
  pro_until    timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Non-obvious column documentation.
comment on column profiles.user_id is
  '1:1 with auth.users.id. Cascade-deletes when the auth user is removed.';
comment on column profiles.friend_code is
  '8-char unambiguous-alphabet handle (ABCDEFGHJKLMNPQRSTUVWXYZ23456789). '
  'Generated by generate_friend_code() inside handle_new_user(). '
  'Lookups for add-friend run under service role; clients cannot enumerate.';
comment on column profiles.is_pro is
  'Cache of RevenueCat entitlement. Source of truth is RevenueCat; this is '
  'flipped by the revenuecat-webhook Edge Function. See data-model.md Open Q #3.';
comment on column profiles.pro_until is
  'Expiry timestamp for is_pro. Null when not Pro. Maintained by the webhook.';
comment on column profiles.updated_at is
  'Touched by the application/webhook when display_name or pro fields change. '
  'No trigger maintains this in v0.2 — writers must set it explicitly.';

-- Index for friend_code lookups (data-model.md §8). The UNIQUE constraint
-- already creates a backing index; this is the explicitly-named one called
-- out in the spec.  `if not exists` so it co-exists with the unique index.
create index if not exists profiles_friend_code_idx on profiles(friend_code);

-- -----------------------------------------------------------------------------
-- 2. friend-code generator (data-model.md §2.1 — "Friend code generation")
-- -----------------------------------------------------------------------------
-- Mirrors lib/multiplayer.ts:26. 32-char unambiguous alphabet (no I/O/0/1),
-- 8 chars → 32^8 ≈ 1.1e12 codes. pgcrypto's gen_random_bytes gives us a
-- crypto-secure source; we mask each byte with & 31 to land in [0,32).
create extension if not exists pgcrypto;

create or replace function generate_friend_code()
  returns text
  language plpgsql
  set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  buf      bytea;
  out_code text := '';
  i        int;
begin
  buf := gen_random_bytes(8);
  for i in 0..7 loop
    -- get_byte is 0-indexed; (b & 31) maps a byte into the 32-char alphabet,
    -- which is the same mask used client-side in lib/multiplayer.ts.
    out_code := out_code || substr(alphabet, (get_byte(buf, i) & 31) + 1, 1);
  end loop;
  return out_code;
end
$$;

comment on function generate_friend_code() is
  'Returns a single random 8-char friend code from the 32-char unambiguous '
  'alphabet (ABCDEFGHJKLMNPQRSTUVWXYZ23456789). Caller is responsible for '
  'retrying on unique_violation — see handle_new_user().';

-- Lock down: no public exec, server callers (trigger runs as definer) only.
revoke all on function generate_friend_code() from public;

-- -----------------------------------------------------------------------------
-- 3. handle_new_user() trigger fn (data-model.md §6 Phase A step 1)
-- -----------------------------------------------------------------------------
-- Runs as security definer so it can insert into profiles despite the
-- client-side INSERT being revoked.  Loops on unique_violation in the
-- astronomical chance of a friend_code collision.
create or replace function handle_new_user()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  code text;
begin
  loop
    code := generate_friend_code();
    begin
      insert into profiles (user_id, friend_code)
      values (new.id, code);
      exit;
    exception when unique_violation then
      -- collision on friend_code (1 in ~10^12); regenerate and retry.
      continue;
    end;
  end loop;
  return new;
end
$$;

comment on function handle_new_user() is
  'auth.users AFTER INSERT trigger. Creates the matching profiles row with a '
  'freshly generated friend_code. Runs as security definer so it can insert '
  'despite client INSERT being revoked.';

revoke all on function handle_new_user() from public;

-- -----------------------------------------------------------------------------
-- 4. on_auth_user_created trigger on auth.users
-- -----------------------------------------------------------------------------
-- Replayability: drop-if-exists then create. (auth.users lives in the auth
-- schema; we need the trigger there, not on public.)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- -----------------------------------------------------------------------------
-- 5. Row Level Security (data-model.md §2.1 Policies table)
-- -----------------------------------------------------------------------------
alter table profiles enable row level security;

-- SELECT: read own only. Friend-code → uuid lookup is service-role-only via
-- the add-friend Edge Function; clients cannot enumerate other rows.
do $$ begin
  create policy "profiles read own" on profiles
    for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

-- UPDATE: own row only. The column-level revoke below restricts WHICH columns
-- can actually be changed (display_name + updated_at in practice; friend_code,
-- is_pro, pro_until are server-managed).
do $$ begin
  create policy "profiles update own basic" on profiles
    for update using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

-- INSERT: no policy. handle_new_user() (security definer) inserts on signup;
-- clients have INSERT revoked outright.
-- DELETE: no policy. Cascade from auth.users is the only removal path.

-- -----------------------------------------------------------------------------
-- 6. Explicit grants (no `grant all` — spec constraint)
-- -----------------------------------------------------------------------------
-- Read + targeted update for end-users; everything else server-side.
grant select on profiles to authenticated;
grant update (display_name, updated_at) on profiles to authenticated;

-- Belt-and-braces: revoke INSERT, DELETE, and the server-managed columns from
-- authenticated, even though no GRANT above hands them out — this makes the
-- intent explicit and survives accidental future broad grants.
revoke insert on profiles from authenticated;
revoke delete on profiles from authenticated;
revoke update (friend_code, is_pro, pro_until) on profiles from authenticated;

-- anon never touches profiles directly.
revoke all on profiles from anon;
